### ISSUE TITLE
Saving checkpoints and final model

### ISSUE THREAD

**Issue by clouedoc** [kamalkraj/minGPT-TF#2]
Hello, is there any way to save checkpoints to a specific file ? Also, how could I save the model for future use via other TF code ?

I'm still getting started learning Tensorflow and Python, so please bear with me 😅 !

Edit: current setup doesn't save checkpoint. Will it save only after each epoch ?

![image](https://user-images.githubusercontent.com/13921610/111845863-fc8ef080-8905-11eb-96cf-e854e895ac25.png)

**Comment by kamalkraj** [comment]
weights are saved after each epoch

**Comment by clouedoc** [comment]
Thanks for the information. I'm now trying to load the checkpoints which were generated this night.
I'll update here when I find how.
![image](https://user-images.githubusercontent.com/13921610/111864042-085ad100-895f-11eb-9980-3a4f6e7999cf.png)

**Comment by clouedoc** [comment]
Found out how to load from checkpoint:

![image](https://user-images.githubusercontent.com/13921610/111865125-802bfa00-8965-11eb-8270-6e300803a5c9.png)
And you just have to replace `trainer.model` by `model` when sampling.
